#!/bin/sh

./BBH_xml.py --seed 3 --distance 2.e10 --coalesTime 178 --outXMLfile data/BBHchallenge1_2_1.xml

./BBH_xml.py --seed 4 --distance 5.e9 --coalesTime 400 --outXMLfile data/BBHchallenge1_2_2.xml

./test-snr.py data/BBHchallenge1_2_1.xml data/BBHchallenge1_2_2.xml

