#!/usr/bin/env python

import sys
import os

gsldir = None

for arg in sys.argv:
    if arg.startswith('--gsl='):
        gsldir = arg.split('=',1)[1]
    elif arg.startswith('--fftw='):
        fftwdir = arg.split('=',1)[1]

if gsldir:
    setpath = ' -I%(gsldir)s/include -L%(gsldir)s/lib' % globals()
else:
    setpath = ''

if fftwdir != gsldir:
    setpath += ' -I%(fftwdir)s/include -L%(fftwdir)s/lib' % globals()

assert(0 == os.system('gcc -O2 -o Fast_Response3 Fast_Response3.c arrays.c AENoise.c -lm -lfftw3' + setpath))

assert(0 == os.system('gcc -O2 -o Galaxy_Maker3 Galaxy_Maker3.c arrays.c AENoise.c -lm -lgsl -lgslcblas' + setpath))

assert(0 == os.system('gcc -O2 -o Galaxy_key3 Galaxy_key3.c   ../../lisaXML/io-C/lisaxml.c ../../lisaXML/io-C/ezxml.c -I../../lisaXML/io-C ../../lisaXML/io-C/xmlbinary.c ../../lisaXML/io-C/readxml.c -lm'))

assert(0 == os.system('gcc -O2 -o Fast_XML_LS3 Fast_XML_LS3.c ../../lisaXML/io-C/lisaxml.c ../../lisaXML/io-C/ezxml.c -I../../lisaXML/io-C ../../lisaXML/io-C/xmlbinary.c ../../lisaXML/io-C/readxml.c -lm'))

assert(0 == os.system('gcc -O2 -o Fast_XML_SL3 Fast_XML_SL3.c ../../lisaXML/io-C/lisaxml.c ../../lisaXML/io-C/ezxml.c -I../../lisaXML/io-C ../../lisaXML/io-C/xmlbinary.c ../../lisaXML/io-C/readxml.c -lm'))
