#!/bin/sh

./EMRI_xml.py --seed 3 --distance 4.e9 --sourceType quiet --time 2 --cadence 15 --outXMLfile data/EMRIa.xml
./EMRI_xml.py --seed 5 --distance 4.e9 --sourceType quiet --time 2 --cadence 15 --outXMLfile data/EMRIb.xml
./EMRI_xml.py --seed 4 --distance 2.e9 --sourceType quiet --time 2 --cadence 15 --outXMLfile data/EMRIc.xml
./EMRI_xml.py --seed 7 --distance 1.e9 --sourceType quiet --time 2 --cadence 15 --outXMLfile data/EMRId.xml
./EMRI_xml.py --seed 6 --distance 1.e9 --sourceType quiet --time 2 --cadence 15 --outXMLfile data/EMRIe.xml

./EMRI_p.py -f data/EMRIa.xml
./EMRI_p.py -f data/EMRIb.xml
./EMRI_p.py -f data/EMRIc.xml
./EMRI_p.py -f data/EMRId.xml
./EMRI_p.py -f data/EMRIe.xml
